# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        article_preview:
            quality: 75
            filters:
                thumbnail: { size: [480, 300], mode: outbound }
        article_detail:
            quality: 100
            filters:
                thumbnail: { size: [750, 500], mode: outbound }
