twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/custom_email_type.html.twig'
        - bootstrap_4_layout.html.twig
    paths:
        'public\images': images
        'assets\styles': css
        '%kernel.project_dir%/templates/partial': partial
when@test:
    twig:
        strict_variables: true
